# Generated by Django 3.2.9 on 2021-11-30 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0002_auto_20210916_1521'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TipoElectrodomestico',
            new_name='TipoProducto',
        ),
    ]
